# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5189a957157763d6fb73ff4f8042cecf818e29d6b4d960dda59b30850f907e04ed5842716632c9a356078e97fcaba339d5ac512dd7770d9d5af40c76c5fb0d5f

test:
  secret_key_base: e02fdab0391eebd35dfedfc4023e1b4566f3a5cce7348b4889c0ad65cfc0b3212e21813ed94ee6d0af1d8bec9384aed4e63fd5a7048c5610958e570ebfc480f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
